"""Merge private-car station curve outputs from parallel vehicle shards."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import pandas as pd

from mobility.cars.station_curves import (
    _combine_count_frames,
    _combine_station_curves,
    build_station_summary_2025,
    export_analysis_files,
    load_existing_station_metadata,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge outputs generated by run_privatecar_charging_curves.py vehicle shards."
    )
    parser.add_argument("--data-dir", type=Path, default=REPO_ROOT / "data")
    parser.add_argument(
        "--shard-root",
        type=Path,
        default=REPO_ROOT / "outputs" / "privatecar_charging_curves_2025_shards",
        help="Directory containing shard output directories.",
    )
    parser.add_argument(
        "--shard-glob",
        default="shard_*",
        help="Glob used under --shard-root to find shard output directories.",
    )
    parser.add_argument(
        "--shard-dir",
        action="append",
        type=Path,
        default=None,
        help="Explicit shard output directory. Can be supplied multiple times.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "outputs" / "privatecar_charging_curves_2025_merged",
    )
    parser.add_argument("--year", type=int, default=2025)
    return parser.parse_args()


def _resolve_shard_dirs(args: argparse.Namespace) -> list[Path]:
    shard_dirs: list[Path] = []
    if args.shard_dir:
        shard_dirs.extend(args.shard_dir)
    if args.shard_root.exists():
        shard_dirs.extend(sorted(path for path in args.shard_root.glob(args.shard_glob) if path.is_dir()))

    unique_dirs: list[Path] = []
    seen: set[Path] = set()
    for path in shard_dirs:
        resolved = path.resolve()
        if resolved not in seen:
            unique_dirs.append(path)
            seen.add(resolved)

    if not unique_dirs:
        raise FileNotFoundError(
            f"No shard directories found under {args.shard_root} with glob {args.shard_glob!r}"
        )
    return unique_dirs


def _read_required_parquet(shard_dir: Path, filename: str) -> pd.DataFrame:
    path = shard_dir / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing required shard output: {path}")
    return pd.read_parquet(path)


def main() -> None:
    args = parse_args()
    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)

    curve_name = f"station_charging_curve_15min_{args.year}.parquet"
    station_counts_name = f"station_counts_{args.year}.parquet"
    station_day_counts_name = f"station_day_counts_{args.year}.parquet"
    failed_name = f"failed_vehicles_{args.year}.csv"
    profile_name = f"profiling_log_{args.year}.csv"

    shard_dirs = _resolve_shard_dirs(args)
    curve_frames: list[pd.DataFrame] = []
    station_count_frames: list[pd.DataFrame] = []
    station_day_count_frames: list[pd.DataFrame] = []
    failed_frames: list[pd.DataFrame] = []
    profile_frames: list[pd.DataFrame] = []
    manifest_shards: list[dict] = []

    for shard_dir in shard_dirs:
        curve = _read_required_parquet(shard_dir, curve_name)
        station_counts = _read_required_parquet(shard_dir, station_counts_name)
        station_day_counts = _read_required_parquet(shard_dir, station_day_counts_name)
        curve_frames.append(curve)
        station_count_frames.append(station_counts)
        station_day_count_frames.append(station_day_counts)

        failed_path = shard_dir / failed_name
        if failed_path.exists():
            failed = pd.read_csv(failed_path)
            failed["source_shard_dir"] = str(shard_dir)
            failed_frames.append(failed)

        profile_path = shard_dir / profile_name
        if profile_path.exists():
            profile = pd.read_csv(profile_path)
            profile["source_shard_dir"] = str(shard_dir)
            profile_frames.append(profile)

        manifest_shards.append(
            {
                "shard_dir": str(shard_dir),
                "station_curve_rows": int(len(curve)),
                "station_count_rows": int(len(station_counts)),
                "station_day_count_rows": int(len(station_day_counts)),
                "energy_kwh": float(curve["energy_kwh"].sum()) if "energy_kwh" in curve.columns else 0.0,
            }
        )

    station_curve = _combine_station_curves(curve_frames)
    station_counts = _combine_count_frames(station_count_frames, ["station_id"])
    station_day_counts = _combine_count_frames(station_day_count_frames, ["station_id", "date"])
    station_metadata = load_existing_station_metadata(args.data_dir)
    station_summary = build_station_summary_2025(
        station_curve,
        station_metadata,
        station_counts,
        year=args.year,
    )

    export_analysis_files(
        station_curve,
        station_summary,
        station_metadata,
        out,
        year=args.year,
        station_counts=station_counts,
        station_day_counts=station_day_counts,
    )

    if failed_frames:
        pd.concat(failed_frames, ignore_index=True).to_csv(out / failed_name, index=False)
    if profile_frames:
        pd.concat(profile_frames, ignore_index=True).to_csv(
            out / f"profiling_log_merged_{args.year}.csv",
            index=False,
        )

    manifest = {
        "schema_version": "1.0",
        "year": args.year,
        "source_shard_count": len(shard_dirs),
        "source_shards": manifest_shards,
        "station_curve_rows": int(len(station_curve)),
        "station_summary_rows": int(len(station_summary)),
        "station_count_rows": int(len(station_counts)),
        "station_day_count_rows": int(len(station_day_counts)),
        "public_station_energy_kwh": float(station_curve["energy_kwh"].sum())
        if not station_curve.empty
        else 0.0,
    }
    (out / f"merge_manifest_{args.year}.json").write_text(
        json.dumps(manifest, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )

    print("\n=== Private-car shard merge outputs ===")
    print(f"output_dir: {out}")
    print(f"source_shards: {len(shard_dirs):,}")
    print(f"station_curve_rows: {len(station_curve):,}")
    print(f"station_summary_rows: {len(station_summary):,}")
    print(f"station_day_count_rows: {len(station_day_counts):,}")
    print(f"public_station_energy_kwh: {manifest['public_station_energy_kwh']:.3f}")
    print(f"manifest: {out / f'merge_manifest_{args.year}.json'}")


if __name__ == "__main__":
    main()
